# Generated by Django 5.1.5 on 2025-01-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aastha_therapy_center', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='physiotherapist',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='preferred_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='preferred_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Physiotherapist',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
