# Generated by Django 5.1.5 on 2025-01-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aastha_therapy_center', '0003_alter_appointment_options_alter_appointment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Admin notes about this appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
